default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: <%= ENV['DB_HOST'] %>
development:
  <<: *default
  database: Ryoma_Elearning_development
test:
  <<: *default
  database: Ryoma_Elearning_test

production:
  adapter: postgresql
  database: e-learning3
  pool: 5
  timeout: 5000
